version: '3.8'
services:
  api:
    build: .
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - APP_ID=${APP_ID}
      - GUILD_ID=${GUILD_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - PORT=${PORT}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO_OWNER=${GITHUB_REPO_OWNER}
      - GITHUB_REPO_NAME=${GITHUB_REPO_NAME}
    volumes:
      - ./src:/usr/src/app/src
      - ./assets:/usr/src/app/assets
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    command: npm run dev-api

  emoji-bot:
    build: .
    environment:
      - NODE_ENV=development
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    volumes:
      - ./src:/usr/src/app/src
      - ./assets:/usr/src/app/assets
    restart: unless-stopped
    command: npm run dev-bot

  migrations:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    volumes:
      - ./knexfile.js:/usr/src/app/knexfile.js
      - ./db/migrations:/usr/src/app/db/migrations
    command: npx knex migrate:latest

  command_registration:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - APP_ID=${APP_ID}
      - GUILD_ID=${GUILD_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - PORT=${PORT}
    volumes:
      - ./src:/usr/src/app/src
    command: npm run register

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    # uses variables defined in .env
    command:
      - "http"
      - "http://host.docker.internal:${PORT}"
      - "--url"
      - "${NGROK_ADDRESS}"
    depends_on:
      api:
        condition: service_started
    ports:
      - 4040:4040

volumes:
  postgres-data:
